apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: myphp
  name: myphp
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: myphp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myphp
    spec:
      containers:
      - image: docker.io/mguazzardo/miphp
        name: miphp
status:
  availableReplicas: 1
