apiVersion: v1
kind: Service
metadata:
  labels:
    app: myphp
  name: myphp
  namespace: default
spec:
  clusterIP: 10.100.27.146
  ports:
  - nodePort: {{ .Values.service.nodePort }} 
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myphp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
